### ISSUE TITLE
Add SCS image metadata

### ISSUE THREAD

**Issue by frosty-geek** [osism/openstack-image-manager#332]
I suggest that we switch to using final meta keywords, in example:

```yaml
  - name: Ubuntu 20.04
    shortname: ubuntu-20.04
    format: qcow2
    login: ubuntu
    min_disk: 8
    min_ram: 512
    status: active
    visibility: public
    multi: true
    meta:
      architecture: x86_64
      hw_disk_bus: scsi
      hw_rng_model: virtio
      hw_scsi_model: virtio-scsi
      hw_watchdog_action: reset
      os_distro: ubuntu
      os_version: '20.04'
    tags: []
    versions:
      - version: '20220804'
        url: https://minio.services.osism.tech/openstack-image-manager/ubuntu-20.04/20220804/focal-server-cloudimg-amd64.img
        source: https://cloud-images.ubuntu.com/focal/20220804/focal-server-cloudimg-amd64.img
        checksum: "sha256:d96622d77bcbab5526fd42e7d933ee851d239327946992a018b0bfc9fad777e7"
```

looking at the [code](https://github.com/osism/openstack-image-manager/blob/main/src/manage.py#L332) ```login``` actually becomes ```image_original_user``` which is a mandatory field in the new [SCS Spec](https://github.com/SovereignCloudStack/Docs/blob/main/Design-Docs/Image-Properties-Spec.md), but there is no documentation that it will be internally mapped.

For the time being a documented mapping table would help to ease the transition...

Comments?
