### ISSUE TITLE
add an optional image id to the images.yaml

### ISSUE THREAD

**Issue by frosty-geek** [osism/openstack-image-manager#348]
I suggest that we add an optional image id to the config so a CSP can ensure that the same Image has the same image id across all self-contained regions.

```yaml
  - name: Ubuntu 22.04
    format: qcow2
    login: ubuntu
    min_disk: 8
    min_ram: 512
    status: active
    visibility: public
    multi: true
    meta:
      architecture: x86_64
      hypervisor_type: qemu
      hw_disk_bus: scsi
      hw_rng_model: virtio
      hw_scsi_model: virtio-scsi
      hw_qemu_guest_agent: yes
      hw_watchdog_action: reset
      replace_frequency: monthly
      hotfix_hours: 0
      uuid_validity: last-3
      provided_until: none
      os_distro: ubuntu
      os_version: '22.04'
    tags: []
    versions:
      - version: '20220923'
        url: https://cloud-images.ubuntu.com/releases/jammy/release-20220923//ubuntu-22.04-server-cloudimg-amd64.img
        checksum: sha256:0fcb96fbfd7120be2f74215fdf47c697aa39453ced5c297028beffab522240f2
        id: 9264c41b-e774-4305-b08e-d1ddd43c075a
      - version: '20220902'
        url: https://cloud-images.ubuntu.com/releases/jammy/release-20220902/ubuntu-22.04-server-cloudimg-amd64.img
        checksum: sha256:c777670007cc5f132417b9e0bc01367ccfc2a989951ffa225bb1952917c3aa81
        id: e88ec821-f37e-4a47-918a-30bfcdda59a4
      - version: '20220810'
        url: https://cloud-images.ubuntu.com/releases/jammy/release-20220810/ubuntu-22.04-server-cloudimg-amd64.img
        checksum: sha256:5ba6b098d2e7b2c4b572812c1df5943187780b64aaa673a0ffde323adba8594b
        id: e7f0114f-016d-4575-b701-95a19b9aa863
```

comments?
