### ISSUE TITLE
URL building still broken

### ISSUE THREAD

**Issue by linwalth** [osism/openstack-image-manager#598]
These URLs were created with an image manager at commit `0137846bdaf99414127de9ff3e5120ce92364c5b`.
The problem with the URLs eating separating slashes persists:

```
    versions:
      - version: '20230516'
        url: https://cloud-images.ubuntu.com/minimal/releases/jammy/release-20230516ubuntu-22.04-minimal-cloudimg-amd64.img
        checksum: sha256:65db2b74ae4481998ce9dbbf90d6ce770b94b486c066529493493e832020d523
        build_date: 2023-05-16
        image_description: https://cloud-images.ubuntu.com/minimal/releases/jammy/release
      - version: '20230530'
        url: https://cloud-images.ubuntu.com/minimal/releases/jammy/release-20230530ubuntu-22.04-minimal-cloudimg-amd64.img
        checksum: sha256:935b1c19f0f8e8ca147fe99d89a1e9bf6f4513e93ea70029e2c1c954312fd8b6
        build_date: 2023-05-30
        image_description: https://cloud-images.ubuntu.com/minimal/releases/jammy/release
      - version: '20230604'
        url: https://cloud-images.ubuntu.com/minimal/releases/jammy/release-20230604ubuntu-22.04-minimal-cloudimg-amd64.img
        checksum: sha256:77e808031361d15de06fe375231c6c5f6f9db281828c87e856d812439940ed39
        build_date: 2023-06-04
        image_description: https://cloud-images.ubuntu.com/minimal/releases/jammy/release

```
