### ISSUE TITLE
Resolve latest URL in update script

### ISSUE THREAD

**Issue by berendt** [osism/openstack-image-manager#639]
On update:

* ``https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img`` --> ``https://cloud-images.ubuntu.com/jammy/20230712/jammy-server-cloudimg-amd64.img``
* set ``url = https://cloud-images.ubuntu.com/jammy/20230712/jammy-server-cloudimg-amd64.img`` 

```
    versions:
      - version: '20230712'
        url:
          https://cloud-images.ubuntu.com/jammy/20230712/jammy-server-cloudimg-amd64.img
        mirror_url:
          https://minio.services.osism.tech/openstack-image-manager/ubuntu-22.04/20230712-ubuntu-22.04.qcow2
        checksum: sha256:d6be2e196cdfea144d0b75f7dec0c5a0970603f01f0365d265be28438ed03352
        build_date: '2023-07-12'
```
