### ISSUE TITLE
Naming scheme mismatch between openstack-image-manager and SCS standard

### ISSUE THREAD

**Issue by markus-hentsch** [osism/openstack-image-manager#753]
The current implementation of assembling image names[^1] in the openstack-image-manager puts a space character between name and version for non-`multi` images.

This seems in conflict with the image naming scheme currently mandated by SCS for the "ubuntu-capi-image"[^2] where a hyphen is expected between name and version.

Consider the following example `images.yaml` as input (content shortened):

```yaml
---
images:
  - name: Ubuntu 22.04
    enable: true
    shortname: ubuntu-22.04
    format: qcow2
    ...
    versions:
      - version: '20240319'
        url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
        checksum: "sha256:304983616fcba6ee1452e9f38993d7d3b8a90e1eb65fb0054d672ce23294d812"
        build_date: 2024-03-19
  - name: ubuntu-capi-image
    enable: true
    format: qcow2
    ...
    tags: []
    versions:
      - version: 'v1.26.11'
        url: https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-k8s-capi-images/ubuntu-2204-kube-v1.26/ubuntu-2204-kube-v1.26.11.qcow2
        checksum: "sha256:ccab58db9581977b1455a27445f7e7f7238ca2457f13464e0d00586dd1f96d6a"
        build_date: 2023-11-16
```

This leads to:

```
+--------------------------------------+----------------------------+--------+
| ID                                   | Name                       | Status |
+--------------------------------------+----------------------------+--------+
| 7b0f58a7-7506-4794-bc29-17ab4c7edd63 | Ubuntu 22.04               | active |
| b1d41496-d68a-4126-bd1a-5c4cc9a0d3dc | ubuntu-capi-image v1.26.11 | active |
+--------------------------------------+----------------------------+--------+
```

... and does not pass the SCS conformance check[^3] as it fails to recognize the "ubuntu-capi-image":

```bash
python3 images-openstack.py --os-cloud devstack scs-0104-v1-images.yaml

INFO: Missing recommended image 'ubuntu-capi-image'
```

[^1]: https://github.com/osism/openstack-image-manager/blob/7d3a433fd5a6f0660d2fdd88145fbfea6a17564f/openstack_image_manager/manage.py#L527-L531

[^2]: https://github.com/SovereignCloudStack/standards/blob/73e9242b78975743291a30a4de5c5450f4e5c7d3/Tests/iaas/scs-0104-v1-images.yaml#L7-L10

[^3]: https://github.com/SovereignCloudStack/standards/blob/73e9242b78975743291a30a4de5c5450f4e5c7d3/Tests/iaas/standard-images/images-openstack.py
