### ISSUE TITLE
add hw_vif_multiqueue_enabled to schema.yaml

### ISSUE THREAD

**Issue by Multigestern** [osism/openstack-image-manager#914]
When I want to add hw_vif_multiqueue_enabled: true to the meta of my image i get a Unexpected element error.

with this config it is added:
````
---
images: list(include('image'), min=1)

---
image:
  enable: bool()
  format: enum('aki', 'ari', 'ami', 'raw', 'iso', 'vhd', 'vdi', 'qcow2', 'vmdk')
  latest_checksum_url: regex(r'^(http|ftp)s?:\/\/\w+.*', name='valid URL', required=False)
  latest_url: regex(r'^(http|ftp)s?:\/\/\w+.*', name='valid URL', required=False)
  login: str()
  meta: include('meta', required=True)
  min_disk: int(min=0)
  min_ram: int(min=0)
  multi: bool()
  keep: bool(required=False)
  name: str()
  password: str(required=False)
  shortname: str(required=False)
  status: enum('active', 'deactivated')
  separator: str(required=False)
  tags: list(str())
  versions: list(include('versions'))
  visibility: enum('public', 'private', 'community', 'shared')

---
meta:
  architecture: enum('x86_64', 'aarch64', 'risc-v')
  hypervisor_type: enum('hyperv', 'ironic', 'lxc', 'qemu', 'uml', 'vmware', 'xen')
  hotfix_hours: int(min=0, required=False)
  hw_disk_bus: enum('virtio', 'scsi', None)
  hw_rng_model: enum('virtio', None, required=False)
  hw_scsi_model: enum('virtio-scsi', required=False)
  hw_watchdog_action: enum('disabled', 'reset', 'poweroff', 'pause', 'none', required=False)
  hw_vif_multiqueue_enabled: bool(required=False)
  image_description: str(required=False)
  os_distro: enum('arch', 'centos', 'cirros', 'clearlinux', 'debian', 'fedora', 'freebsd', 'opensuse', 'rhel', 'talos', 'ubuntu', 'windows')
  os_version: str(required=False)
  patchlevel: str(required=False)
  provided_until: any(enum('none'), day())
  replace_frequency: enum('yearly', 'quarterly', 'monthly', 'weekly', 'daily', 'critical_bug', 'never')
  uuid_validity: any(enum('none', 'forever', 'notice'), str(starts_with='last-'), day())

---
versions:
  build_date: any(day(), timestamp())
  checksum: regex(r'\w+:([a-f0-9]{32}|[a-f0-9]{40}|[a-f0-9]{64}|[a-f0-9]{128})$', name='valid checksum', required=False)
  checksums_url: regex(r'^(http|ftp)s?:\/\/\w+.*', name='valid URL', required=False)
  hidden: bool(required=False)
  image_description: str(required=False)
  meta: include('meta', required=False)
  os_version: str(required=False)
  source: regex(r'^(http|ftp)s?:\/\/\w+.*|^private$', name='valid URL or private', required=False)
  url: regex(r'^(http|ftp)s?:\/\/\w+.*|^(file:|file:///)\w+.*', name='valid URL')
  mirror_url: regex(r'^(http|ftp)s?:\/\/\w+.*|^(file:|file:///)\w+.*', name='valid URL', required=False)
  version: str()
  visibility: enum('public', 'private', 'community', 'shared', required=False)
  id: regex(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', required=False)
```
